---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: bash -c 'storm version'
      register: test_storm_version
    - name: storm version
      debug:
        msg: '{{ test_storm_version.stdout }}'
