---
- name: Testing andrewrothstein.storm
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'storm version'
      ansible.builtin.command: bash -lc 'storm version'
      changed_when: false
      register: test_storm_version
    - name: Output of 'storm version'
      ansible.builtin.debug:
        msg: '{{ test_storm_version.stdout }}'
