---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Installing andrewrothstein.bash
  ansible.builtin.include_role:
    name: andrewrothstein.bash
- name: Installing andrewrothstein.temurin
  ansible.builtin.include_role:
    name: andrewrothstein.temurin
  vars:
    openjdk_app: jre
- name: Checking for install in {{ storm_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ storm_install_dir }}'
  register: storm_binary
- name: Downloading and installing apache storm
  when: not storm_binary.stat.exists
  block:
    - name: Downloading {{ storm_url }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ storm_url }}'
        dest: '{{ storm_tmp_tgz }}'
        mode: '644'
        checksum: '{{ storm_checksum }}'
    - name: Unarchive {{ storm_tmp_tgz }} to {{ storm_parent_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ storm_tmp_tgz }}'
        dest: '{{ storm_parent_dir }}'
        creates: '{{ storm_install_dir }}'
  always:
    - name: Rm {{ storm_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ storm_tmp_tgz }}'
        state: absent

- name: Linking {{ storm_install_link_dir }} to {{ storm_install_dir }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ storm_install_dir }}'
    dest: '{{ storm_install_link_dir }}'
    state: link
- name: Include storm in the default path...
  become: true
  become_user: root
  with_items:
    - f: storm.sh
      d: /etc/profile.d
  ansible.builtin.template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("644") }}'
