---
- name: download...
  become: yes
  become_user: root
  get_url:
    url: '{{storm_url}}'
    dest: /tmp/{{storm_tgz}}
    mode: '0644'
    checksum: '{{storm_checksum}}'

- name: unarchive...
  become: yes
  become_user: root
  unarchive:
    copy: no
    src: /tmp/{{storm_tgz}}
    dest: '{{storm_parent_dir}}'
    creates: '{{storm_install_dir}}'

- name: linking...
  become: yes
  become_user: root
  file:
    src: '{{storm_install_dir}}'
    dest: '{{storm_install_link_dir}}'
    state: link

- name: include storm in the default path...
  become: yes
  become_user: root
  with_items:
    - f: storm.sh
      d: /etc/profile.d
  template:
    src: '{{item.f}}.j2'
    dest: '{{item.d}}/{{item.f}}'
    mode: '{{item.m|default("0644")}}'
    
