---
- name: check for install in {{ storm_install_dir }}
  become: true
  stat:
    path: '{{ storm_install_dir }}'
  register: storm_binary
- when: not storm_binary.stat.exists
  block:
    - name: downloading {{ storm_url }}
      become: true
      become_user: root
      get_url:
        url: '{{ storm_url }}'
        dest: '{{ storm_tmp_tgz }}'
        mode: '0644'
        checksum: '{{ storm_checksum }}'

    - name: unarchive {{ storm_tmp_tgz }} to {{ storm_parent_dir }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ storm_tmp_tgz }}'
        dest: '{{ storm_parent_dir }}'
        creates: '{{ storm_install_dir }}'

    - name: linking {{ storm_install_link_dir }} to {{ storm_install_dir }}
      become: true
      become_user: root
      file:
        src: '{{ storm_install_dir }}'
        dest: '{{ storm_install_link_dir }}'
        state: link
  always:
    - name: rm {{ storm_tmp_tgz }}
      become: true
      become_user: root
      file:
        path: '{{ storm_tmp_tgz }}'
        state: absent

- name: include storm in the default path...
  become: true
  become_user: root
  with_items:
    - f: storm.sh
      d: /etc/profile.d
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m|default("0644") }}'
