---
- name: download...
  become: yes
  become_user: root
  get_url: >
    url={{storm_url}}
    dest=/tmp/{{storm_archive}}
    mode=0644

- name: unarchive...
  become: yes
  become_user: root
  unarchive: >
    copy=no
    src=/tmp/{{storm_archive}}
    dest=/opt
    creates=/opt/{{storm_name}}

- name: link /opt/storm...
  become: yes
  become_user: root
  file: >
    src=/opt/{{storm_name}}
    dest=/opt/storm
    state=link

- name: include storm in the default path...
  become: yes
  become_user: root
  with_items:
    - etc/profile.d/storm.sh
  copy: >
    src={{item}}
    dest=/{{item}}
    mode=0644
    