---
- name: download storm...
  environment: proxy_env
  get_url: url='{{ storm_url }}' dest='/tmp/{{ storm_archive }}'

- name: install storm...
  unarchive: copy=no src='/tmp/{{ storm_archive }}' dest='/opt'

- name: link /opt/storm...
  file: src='/opt/{{ storm_name }}' dest=/opt/storm state=link

- name: include storm in the default path...
  copy: src='etc/profile.d/storm.sh' dest='/etc/profile.d/storm.sh' mode=644